version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pms
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8080"
volumes:
  db_data:
